# Generated by Django 4.2 on 2025-07-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='pacotes/')),
                ('cafe_da_manha', models.BooleanField(default=False)),
                ('translados', models.BooleanField(default=False)),
                ('hospedagem', models.BooleanField(default=False)),
                ('viagem', models.BooleanField(default=False)),
            ],
        ),
    ]
