# Generated by Django 5.2.4 on 2025-07-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_cupom'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaisProcurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='mais_procurados/')),
                ('descricao1', models.CharField(blank=True, max_length=100)),
                ('descricao2', models.CharField(blank=True, max_length=100)),
                ('descricao3', models.CharField(blank=True, max_length=100)),
                ('descricao4', models.CharField(blank=True, max_length=100)),
                ('botao_texto', models.CharField(default='VER MAIS!', max_length=50)),
                ('botao_link', models.URLField(blank=True)),
            ],
        ),
    ]
