# Generated by Django 5.2.4 on 2025-08-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_passeio'),
    ]

    operations = [
        migrations.AddField(
            model_name='passeio',
            name='descricao_longa',
            field=models.TextField(default=''),
        ),
    ]
