# Generated by Django 5.2.4 on 2025-08-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_passeio_descricao_longa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='promocoes/')),
            ],
        ),
    ]
