# Generated by Django 5.2.4 on 2025-08-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_promocao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passeio',
            name='descricao_curta',
        ),
        migrations.RemoveField(
            model_name='passeio',
            name='descricao_longa',
        ),
        migrations.RemoveField(
            model_name='passeio',
            name='preco',
        ),
        migrations.AddField(
            model_name='passeio',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='passeio',
            name='horarios',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='passeio',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='passeio',
            name='redes_sociais',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='passeio',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='passeio',
            name='valores',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
