# Generated by Django 4.2 on 2025-08-05 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_passeio_descricao_curta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passeio',
            name='mapa_link',
            field=models.URLField(blank=True, help_text='Cole o link do Google Maps aqui'),
        ),
        migrations.CreateModel(
            name='PasseioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='passeios/galeria/')),
                ('passeio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='Home.passeio')),
            ],
        ),
    ]
