# Generated by Django 4.2 on 2025-08-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_passeio_mapa_link_passeioimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passeio',
            name='mapa_link',
            field=models.URLField(blank=True, help_text='Cole o link do Google Maps aqui', max_length=500),
        ),
    ]
