# Generated by Django 4.2 on 2025-08-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_passeio_mapa_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='hospedagens/')),
                ('descricao', models.TextField(default='')),
                ('localizacao', models.CharField(blank=True, max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('valores', models.CharField(blank=True, max_length=100)),
                ('horarios', models.CharField(blank=True, max_length=100)),
                ('redes_sociais', models.URLField(blank=True)),
                ('mapa_link', models.URLField(blank=True, help_text='Cole o link do Google Maps aqui', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HospedagemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='hospedagens/galeria/')),
                ('hospedagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='Home.hospedagem')),
            ],
        ),
    ]
