# Generated by Django 5.2.4 on 2025-08-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maisprocurado',
            name='botao_link',
        ),
        migrations.AddField(
            model_name='maisprocurado',
            name='passeio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.passeio'),
        ),
    ]
